In [1]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [2]:
type(arr1)

list

In [3]:
arr1[0]

'pune'

In [4]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
print(arr2)

[10 20 30 40 50]


In [7]:
arr2

array([10, 20, 30, 40, 50])

In [8]:
arr3 = numpy.array((100,200,300,400,500))

In [9]:
type(arr3)

numpy.ndarray

In [10]:
import numpy as np
a0 = np.array(10)

In [11]:
print(a0)

10


In [12]:
a0.ndim         # returns the dimension of array

0

In [13]:
a0

array(10)

In [14]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [15]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a1.ndim

1

In [18]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [19]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [20]:
a2.ndim

2

In [22]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [23]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [24]:
a3.ndim

3

In [25]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [26]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [27]:
a4.ndim

4

In [28]:
arr2[1]  [10,20,30,40,50]

IndexError: invalid index to scalar variable.

In [29]:
a2[1,2] [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

IndexError: invalid index to scalar variable.

In [30]:
a2[2,2]

np.int64(300)

In [31]:
a3[0,0,0] [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

IndexError: invalid index to scalar variable.

In [32]:
a4[0,0,0,3]

np.int64(4444)

In [33]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [34]:
a12 = np.array([1,2,3])

In [35]:
a12[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [36]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [37]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
arr2

array([10, 20, 30, 40, 50])

In [39]:
arr2[-1]

np.int64(50)

In [42]:
arr2[-2]

np.int64(40)

In [43]:
arr2[1:]

array([20, 30, 40, 50])

In [44]:
arr2[:3]

array([10, 20, 30])

In [45]:
arr2[:]

array([10, 20, 30, 40, 50])

In [46]:
arr2[1:4:1]

array([20, 30, 40])

In [ ]:
arr2[1:4:2]

In [47]:
arr2[:4:3]

array([10, 40])

In [48]:
arr2[::4]

array([10, 50])

In [49]:
arr2[::]

array([10, 20, 30, 40, 50])

In [50]:
for i in arr2:
  print(i)

10
20
30
40
50
